name: Deploy ERP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www/app

            git pull origin main

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force

            php artisan optimize:clear
            php artisan optimize

            chown -R www-data:www-data storage bootstrap/cache
            chmod -R 775 storage bootstrap/cache

            systemctl restart php8.2-fpm
            systemctl restart nginx
